---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: op-bazzite-dx-nvidia-open
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-open
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: keys
        destination: /tmp/keys # copies files/keys/* into /tmp/keys/ in the image
      - source: rpms
        destination: /tmp/rpms # copies files/rpms/* into /tmp/rpms/ in the image
      - source: prebuilt-modules
        destination: /tmp/prebuilt-modules # copies files/prebuilt-modules/* into /tmp/prebuilt-modules/ in the image

  # Custom DisplayLink EVDI installation script
  - type: displaylink
    source: local
    options:
      kernel_version: 6.15.4-106.bazzite.fc42.x86_64 # specify the kernel version use from prebuilt modules
      rpm_package: /tmp/rpms/fedora-42-displaylink-1.14.10-1.github_evdi.x86_64.rpm
      signing_keys_dir: /tmp/keys
      evdi_git_repo: https://github.com/DisplayLink/evdi.git
      cleanup_build_deps: true

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

